### ISSUE TITLE
photoStore 초기화 전 테이블뷰의 viewDidLoad가 되어 전혀 나오지 않는 문제 해결

### ISSUE THREAD

**Issue by wnstkdyu** [RodoPacaGiraffe/BoostCamp_iOS_Picka#10]

**Comment by wnstkdyu** [comment]
테이블 뷰 viewDidLoad 때 Notification의 옵져버 추가하고 인증을 요청받은 뒤 인증이 되었다면 그 때 photoStore를 초기화 실행. fetch, classfiy가 되었을시 완료되었다는 Notification을 날리면 그 때 tableView reload를 실행.

**Comment by wnstkdyu** [comment]
인증이 안 되었을시 설정에서 바꿀 수 있도록하는 AlertView도 띄워야 함.

**Comment by Hoontopia** [comment]
노티피케이션을 통해 viewDidLoad 이후에 테이블뷰가 노티피케이션을 받아 갱신되도록 구현
